old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.test_producer' service to send data.
        test:
            connection:       default
            exchange_options: { name: 'test', type: direct }
        testgo:
            connection:       default
            exchange_options: { name: 'testgo', type: direct }
    consumers:
        test:
            connection:       default
            exchange_options: { name: 'test', type: direct }
            queue_options:    { name: 'test'}
            callback:         App\Consumer\TestConsumer
