#vcrvcr:
#    enabled: true
#    library_hooks:
#        stream_wrapper: true
#        curl: false
#        soap: false
#    request_matchers:
#        method: true
#        url: true
#        query_string: true
#        host: true
#        headers: true
#        body: true
#        post_fields: true
#    cassette:
#        type: json
#        path: '%kernel.cache_dir%/tests/cassetes'
#        name: vcr