# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:

    s-hakaton-nginx:
        container_name: s-hakaton-nginx
        # используем последний стабильный образ nginx
        image: nginx:stable

        restart: unless-stopped
        # маршрутизируем порты
        ports:
            - "81:80"
#            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./..:/var/www/hakaton
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - s-hakaton-php

    s-hakaton-php:
        container_name: s-hakaton-php

        restart: unless-stopped

        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build:
            context: ./
            dockerfile: ./images/php/Dockerfile
        # этот образ будет общаться с mysql
        # монтируем директорию с проектами
        volumes:
            - ./..:/var/www/hakaton
            # Подключим логи
            - ./logs:/var/log/nginx
            #исключим вендоры из расшаренной папки (сделао для исключения виндусятников, т.к там тормозит файловая система)
            #- /var/www/hakaton/vendor/
        links:
            - s-hakaton-db
            - s-hakaton-rabbitmq
          #- hakaton-elastic
          #- hakaton-redis
        ports:
            - "9502:9502"
            - "9501:9501"
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
    s-hakaton-db:
        #user: '0:0'
        container_name: s-hakaton-db
        image: postgres
        restart: unless-stopped
        volumes:
            - pgdata:/var/lib/postgresql/data/hakaton
        environment:
            POSTGRES_PASSWORD: hakaton
            POSTGRES_DB: hakaton
            POSTGRES_USER: hakaton
            POSTGRES_HOST: pg.example_net
            POSTGRES_PORT: 5432
            PGDATA: /var/lib/postgresql/data/hakaton
        ports:
            - "5437:5432"
    s-hakaton-rabbitmq:
        restart: unless-stopped

        container_name: s-hakaton-rabbitmq
        image: rabbitmq:3.7.5-management
        hostname: app-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./volumes/rabbitmq:/var/lib/rabbitmq/mnesia
        environment:
            RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: /

#    yarn:
#        restart: unless-stopped
#        image: node:current-alpine
#        working_dir: /app
#        command: /bin/sh -c 'yarn && yarn watch'
#        volumes:
#            - ./..:/app:rw
volumes:
    pgdata:
        driver: local