# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    app-composer:
        restart: 'no'
        image: composer:latest
        command: install --ignore-platform-reqs -o
        working_dir: /var/www/hakaton
        volumes:
            - ./..:/var/www/hakaton
    app-nginx:
        container_name: app-nginx
        # используем последний стабильный образ nginx
        image: nginx:stable

        restart: unless-stopped
        # маршрутизируем порты
        ports:
            - "81:80"
#            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./..:/var/www/hakaton
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - app-php

    app-php:
        container_name: app-php

        restart: unless-stopped

        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build:
            context: ./
            dockerfile: ./images/php/Dockerfile
        # этот образ будет общаться с mysql
        # монтируем директорию с проектами
        volumes:
            - ./..:/var/www/hakaton
            # Подключим логи
            - ./logs:/var/log/nginx
        links:
            - app-db
            - app-rabbitmq
          #- app-elastic
            - app-redis
        ports:
            - "9502:9502"
            - "9501:9501"
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"

    app-redis:
        restart: unless-stopped
        volumes:
            -  ./volumes/redis:/data
        container_name: app-redis
        ports:
            - "6379:6379"
        image: redis:5.0.5

    #    app-elastic:
    #        restart: unless-stopped
    #
    #        container_name: app-elastic
    #        image: elasticsearch:7.2.0
    #        volumes:
    #            - ./volumes/elastic:/usr/share/elasticsearch/data
    #        ports:
    #            - 11211:11211
    #            - "9200:9200"

    app-db:
        #user: '0:0'
        container_name: app-db
        image: postgres
        restart: unless-stopped
        volumes:
            - pgdata:/var/lib/postgresql/data/hakaton
        environment:
            POSTGRES_PASSWORD: hakaton
            POSTGRES_DB: hakaton
            POSTGRES_USER: hakaton
            POSTGRES_HOST: pg.example_net
            POSTGRES_PORT: 5432
            PGDATA: /var/lib/postgresql/data/hakaton
        ports:
            - "5437:5432"
    app-rabbitmq:
        restart: unless-stopped

        container_name: app-rabbitmq
        image: rabbitmq:3.7.5-management
        hostname: app-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./volumes/rabbitmq:/var/lib/rabbitmq/mnesia
        environment:
            RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: /

    app-yarn:
        container_name: app-yarn
        restart: unless-stopped
        image: node:current-alpine
        working_dir: /app
        command: /bin/sh -c 'yarn && yarn watch'
        volumes:
            - ./..:/app
volumes:
    pgdata:
        driver: local